services:
  database:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  database_populator:
    build:
      context: ..
      dockerfile: deploy/database_populator/Dockerfile
    image: 961341546462.dkr.ecr.eu-west-3.amazonaws.com/planspiel-app/database_populator:latest
    restart: no
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: root
    networks:
      - mynetwork
  data_controller:
    build:
      context: ..
      dockerfile: deploy/data_controller/Dockerfile
    image: 961341546462.dkr.ecr.eu-west-3.amazonaws.com/planspiel-app/data_controller:latest
    restart: always
    environment:
      PLANSPIEL_DATA_CONTROLLER_PORT: 5001
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: data_controller_user
    ports:
      - "5001:5001"
    networks:
      - mynetwork
  game_controller:
    build:
      context: ..
      dockerfile: deploy/game_controller/Dockerfile
    image: 961341546462.dkr.ecr.eu-west-3.amazonaws.com/planspiel-app/game_controller:latest
    restart: always
    environment:
      PLANSPIEL_GAME_CONTROLLER_PORT: 5002
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: game_controller_user
    ports:
      - "5002:5002"
    networks:
      - mynetwork
#  planspiel_prototype:
#    build:
#      context: ..
#      dockerfile: deploy/planspiel_prototype/Dockerfile
#    image: 961341546462.dkr.ecr.eu-west-3.amazonaws.com/planspiel-app/planspiel_prototype:latest
#    restart: always
#    environment:
#      NEXT_PUBLIC_AWS_INSTANCE_ADDR_HTTP: "http://localhost"
#    ports:
#      - "3000:3000"

networks:
  mynetwork:
